# Generated by Django 5.2.15 on 2026-06-22 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='clave')),
                ('value', models.IntegerField(verbose_name='valor')),
            ],
            options={
                'verbose_name': 'parámetro de juego',
                'verbose_name_plural': 'parámetros de juego',
                'db_table': 'game_setting',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='GameSettingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('key', models.CharField(db_index=True, max_length=64, verbose_name='clave')),
                ('value', models.IntegerField(verbose_name='valor')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_setting_changes', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'historial de parámetro',
                'verbose_name_plural': 'historial de parámetros',
                'db_table': 'game_setting_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
