# Generated by Django 5.2.15 on 2026-06-22 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('mode', models.CharField(choices=[('teams', 'Equipos'), ('duel', 'Duelo')], max_length=10, verbose_name='modo')),
                ('config', models.JSONField(default=dict, verbose_name='configuración')),
                ('status', models.CharField(choices=[('active', 'En curso'), ('finished', 'Finalizada')], db_index=True, default='active', max_length=10, verbose_name='estado')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='iniciada el')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finalizada el')),
            ],
            options={
                'verbose_name': 'partida',
                'verbose_name_plural': 'partidas',
                'db_table': 'game',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('name', models.CharField(max_length=20, verbose_name='nombre')),
                ('avatar', models.CharField(blank=True, max_length=8, verbose_name='avatar')),
                ('score', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='puntaje')),
                ('streak', models.PositiveSmallIntegerField(default=0, verbose_name='racha')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='games.game', verbose_name='partida')),
            ],
            options={
                'verbose_name': 'equipo',
                'verbose_name_plural': 'equipos',
                'db_table': 'game_team',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('scene_number', models.PositiveSmallIntegerField(verbose_name='número de escena')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('acting', 'Actuando'), ('guessed', 'Adivinada'), ('failed', 'Fallida'), ('stolen', 'Robada'), ('passed', 'Pasada')], default='pending', max_length=10, verbose_name='estado')),
                ('time_used', models.PositiveSmallIntegerField(default=0, verbose_name='tiempo usado (s)')),
                ('speed_bonus', models.BooleanField(default=False, verbose_name='bonus de velocidad')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='games.game', verbose_name='partida')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turns', to='movies.movie', verbose_name='película')),
                ('stolen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stolen_turns', to='games.team', verbose_name='robada por')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='games.team', verbose_name='equipo')),
            ],
            options={
                'verbose_name': 'turno',
                'verbose_name_plural': 'turnos',
                'db_table': 'game_turn',
                'ordering': ['scene_number', 'id'],
            },
        ),
    ]
