# Generated by Django 5.2.15 on 2026-06-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='slug')),
                ('emoji', models.CharField(blank=True, max_length=8, verbose_name='emoji')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'colección',
                'verbose_name_plural': 'colecciones',
                'db_table': 'movie_collection',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('imdb_id', models.CharField(max_length=20, unique=True, verbose_name='ID IMDb')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('title_es', models.CharField(blank=True, max_length=255, verbose_name='título en español')),
                ('year', models.PositiveSmallIntegerField(verbose_name='año')),
                ('poster_path', models.CharField(blank=True, max_length=500, verbose_name='ruta local del poster')),
                ('poster_url', models.URLField(blank=True, verbose_name='URL del poster en OMDb')),
                ('genres', models.JSONField(blank=True, default=list, verbose_name='géneros')),
                ('level', models.CharField(choices=[('casual', 'Espectador Casual'), ('conocedor', 'Conocedor'), ('loco', 'Loco por las Películas'), ('cinefilo', 'Cinéfilo')], db_index=True, max_length=20, verbose_name='nivel')),
                ('collections', models.JSONField(blank=True, default=list, verbose_name='colecciones (slugs)')),
                ('imdb_rating', models.FloatField(default=0, verbose_name='rating IMDb')),
                ('imdb_votes', models.PositiveIntegerField(default=0, verbose_name='votos IMDb')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'película',
                'verbose_name_plural': 'películas',
                'db_table': 'movie',
                'ordering': ['-imdb_votes'],
                'indexes': [models.Index(fields=['level', 'is_active'], name='movie_level_1da164_idx')],
            },
        ),
    ]
