# Generated by Django 5.2.15 on 2026-09-16 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado el"),
                ),
                ("name", models.CharField(max_length=20, verbose_name="nombre")),
                (
                    "token",
                    models.CharField(
                        db_index=True, max_length=32, verbose_name="token"
                    ),
                ),
                ("board", models.JSONField(default=list, verbose_name="tablero")),
                ("marked", models.JSONField(default=list, verbose_name="marcadas")),
                ("is_winner", models.BooleanField(default=False, verbose_name="ganó")),
                (
                    "connected",
                    models.BooleanField(default=False, verbose_name="conectado"),
                ),
            ],
            options={
                "verbose_name": "jugador de lotería",
                "verbose_name_plural": "jugadores de lotería",
                "db_table": "loteria_player",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado el"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=6, unique=True, verbose_name="código"
                    ),
                ),
                (
                    "host_token",
                    models.CharField(max_length=32, verbose_name="token del anfitrión"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lobby", "Esperando jugadores"),
                            ("playing", "En curso"),
                            ("finished", "Terminada"),
                        ],
                        db_index=True,
                        default="lobby",
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                ("deck", models.JSONField(default=list, verbose_name="baraja")),
                (
                    "drawn_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="cartas cantadas"
                    ),
                ),
                (
                    "draw_interval_ms",
                    models.PositiveIntegerField(
                        default=4000, verbose_name="intervalo entre cartas (ms)"
                    ),
                ),
                ("paused", models.BooleanField(default=False, verbose_name="pausada")),
                (
                    "round_number",
                    models.PositiveIntegerField(default=1, verbose_name="ronda"),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="won_rooms",
                        to="loteria.player",
                        verbose_name="ganador",
                    ),
                ),
            ],
            options={
                "verbose_name": "sala de lotería",
                "verbose_name_plural": "salas de lotería",
                "db_table": "loteria_room",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="player",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="loteria.room",
                verbose_name="sala",
            ),
        ),
        migrations.AddConstraint(
            model_name="player",
            constraint=models.UniqueConstraint(
                fields=("room", "name"), name="loteria_unique_player_name_per_room"
            ),
        ),
    ]
